CREATE DATABASE flvDb;
USE flvDb;
CREATE TABLE pet (name VARCHAR(20), owner VARCHAR(20), species VARCHAR(20), sex CHAR(1), birth DATE);
INSERT INTO pet VALUES ('Puffball','Diane','hamster','f','1999-03-30');
INSERT INTO pet VALUES ('Jack','Peter','dog','m','1999-03-30');
UPDATE pet SET birth = '1989-08-31' WHERE name = 'Jack';
ALTER TABLE pet ADD COLUMN color VARCHAR(20);
DELETE from pet where name="Puffball";
INSERT INTO pet VALUES ("Spot", "Jane", "dog", "m", "2010-11-2", Null);
UPDATE pet SET color="White" WHERE name="Spot";
